### ISSUE TITLE
can not read property 'button' of null

### ISSUE THREAD

**Issue by FunnyZ** [tomwanzek/d3-ng2-demo#27]
i do my demo just like drag-zoom-2.component.ts, but it also can not use.
```ts
function zoomed(this: SVGSVGElement) {
      let e: D3ZoomEvent<SVGSVGElement, any> = d3.event;
      d3G.attr('transform', e.transform.toString());
    }
...
if (this.parentNativeElement !== null) {
      d3ParentElement = d3.select(this.parentNativeElement);

      this.d3Svg = d3ParentElement.select<SVGSVGElement>('svg');
      this.d3Svg.attr('width', width + margin.left + margin.right);
      this.d3Svg.attr('height', height + margin.top + margin.bottom);

      d3G = this.d3Svg.append<SVGGElement>('g');
      d3G.attr('transform', 'translate(' + margin.left + ',' + margin.top + ')');

      let treeMap = d3.tree().size([height, width]);
      let nodes;
      nodes = d3.hierarchy(treeData, d => d.children);
      nodes = treeMap(nodes);

      let link = d3G.selectAll('.link')
        .data(nodes.descendants().slice(1))
        .enter()
        .append('path')
        .attr('class', 'link')
        .style('stroke', d => d['data']['level'])
        .attr('d', d => diagonal(d));

      let node = d3G.selectAll('.node')
        .data(nodes.descendants())
        .enter()
        .append<SVGGElement>('g')
        .attr('class', d => {
          return 'node' + (d['children'] ? ' node--internal' : ' node--leaf');
        })
        .attr('transform', d => 'translate(' + d['y'] + ',' + d['x'] + ')');

      node.append<SVGCircleElement>('circle')
        .attr('r', d => d['data']['value'])
        .style('stroke', d => d['data']['type'])
        .style('fill', d => d['data']['level']);

      node.append('text')
        .attr('dy', '.35em')
        .attr('x', d => {
          return d['children'] ? (d['data']['value'] + 4) * -1 : d['data']['value'] + 4;
        })
        .style('text-anchor', d => d['children'] ? 'end' : 'start')
        .text(d => d['data']['name']);

      this.d3Svg.call(d3.zoom<SVGSVGElement, any>()
        .scaleExtent([1 / 2, 8])
        .on('zoom', zoomed));
    }
```
my d3-ng2-service version: 2.0.0.
Thanks for help!

**Comment by tomwanzek** [comment]
Could you kindly give me some more detail, where the error you experience is thrown. If it's compile time, please identify the line and complete TS error message. If it's runtime a more complete stacktrace that would allow me to understand where the error originated.

Preferably, if you have a repro-repo that I can look at to see if there is an issue arising from the d3-ng2-service, that would probably be the easiest.

My suspicion is that it might be related to `d3.event` somehow loosing a live-binding. I have seen this happen when **d3-selection** gets imported twice (e.g. through the d3 bundle and stand-alone as well.)

**Comment by FunnyZ** [comment]
@tomwanzek 
Sorry, i'm late.
Here is my error message:
stack:"TypeError: Cannot read property 'button' of null\n    at SVGSVGElement.defaultFilter (webpack-internal:///../../../../d3-zoom/src/zoom.js:22:71)\n    at SVGSVGElement.mousedowned (webpack-internal:///../../../../d3-zoom/src/zoom.js:267:32)\n    at SVGSVGElement.eval (webpack-internal:///../../../../d3-ng2-service/node_modules/d3-selection/src/selection/on.js:29:16)\n    at ZoneDelegate.invokeTask (webpack-internal:///../../../../zone.js/dist/zone.js:398:31)\n    at Object.onInvokeTask (webpack-internal:///../../../core/esm5/core.js:4813:33)\n    at ZoneDelegate.invokeTask (webpack-internal:///../../../../zone.js/dist/zone.js:397:36)\n    at Zone.runTask (webpack-internal:///../../../../zone.js/dist/zone.js:165:47)\n    at SVGSVGElement.ZoneTask.invoke (webpack-internal:///../../../../zone.js/dist/zone.js:460:38)"

This happen when i click or mouse scroll the svg.
I see the [d3-selection document](https://github.com/d3/d3-selection#event) and it said:
> An import of d3.event must be a live binding, so you may need to configure the bundler to import from D3’s ES6 modules rather than from the generated UMD bundle; not all bundlers observe jsnext:main. Also beware of conflicts with the window.event global.

finally, i use
```ts
import * as d3Selection from 'd3-selection;
...
d3ParentElement = d3Selction.select(this.parentNativeElement);    // use d3Selection instead of d3
```
and it is ok.

**Comment by tomwanzek** [comment]
As I suspected, your issue seems to boil down to how you import the D3 modules into your component.

The d3-ng2-demo is built using [d3-ng2-service](https://github.com/tomwanzek/d3-ng2-service). So D3 gets injected as an Angular service. The way the service is built in turn and provisioning it in the "root" module ensures that the live binding to `d3.event` is maintained.

While you do not have to use the d3-ng2-service, as its D3 scope may be too wide/narrow for your application, the pattern how it is built is the only surefire way to ensure D3 modules that access d3.event will work consistently. I.e. follow the re-export barrel + Angular service pattern to integrate D3 into an angular project, whenever you need to use any of the following modules:

* d3-selection
* d3-transition
* d3-brush
* d3-drag
* d3-zoom
* d3-dispatch

For the other D3 modules you could simply import them into a D3 component directly. They do not touch DOM/event handling.

Hope this helps. I am going to close this issue here, as there is no bug with the repo. If you have further questions please use StackOverflow. 😄
